@'
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
'@ | Set-Content docker/grafana/provisioning/datasources/prometheus.yml -Encoding UTF8
